### ISSUE TITLE
nothing happens when players are ready

### ISSUE THREAD

**Issue by Doriginal** [Zebbeni/alien-empire#17]
hi,
Thank you for the game.

nothing happens when players are ready
![capture](https://cloud.githubusercontent.com/assets/1387182/10573945/438bfc1a-7653-11e5-8b7a-2f88c36ca41f.JPG)

**Comment by Zebbeni** [comment]
@Doriginal Thanks for taking a look. It looks like I committed a branch to master that was pointing at local versions of jquery, easeljs and preloadjs. If you swap those 3 script references for the 3 commented ones in the index.html file, everything should load correctly (I'll be pushing a commit up with the fix as soon as I have a better connection later this week)

**Comment by Zebbeni** [comment]
@Doriginal Should be fixed now, pushed up a commit with online versions of everything: https://github.com/Zebbeni/alien-empire/commit/28f874acb4aca8e21e34af7fb6477be3c9643c94
